version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10
    target-branch: main
    labels:
      - dependabot
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timer: "04:15"
    target-branch: main
    labels:
      - dependabot
