name: Deploy dev

permissions:
  id-token: write
  contents: read

on: workflow_dispatch

jobs:
  run-checks:
    uses: ./.github/workflows/run-checks.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SAM_APP_VALIDATE_ROLE_ARN: ${{ secrets.SAM_APP_VALIDATE_ROLE_ARN }}
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: run-checks
    with:
      BASE_IMAGE_TAG: rp-stub-dev
    secrets:
      GH_ACTIONS_ROLE_ARN: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
      CONTAINER_SIGNER_KMS_KEY: ${{ secrets.CONTAINER_SIGNER_KMS_KEY }}
      ECR_REPO: ${{ secrets.DEV_ECR_REPOSITORY }}
      ARTIFACT_SOURCE_BUCKET: ${{ secrets.DEV_ARTIFACT_SOURCE_BUCKET_NAME }}
      SIGNING_PROFILE_NAME: ${{ secrets.SIGNING_PROFILE_NAME }}
